version: "3.8"

services:
  main:
    labels:
      svc: "app.gateway"
    container_name: "app.gateway"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"