version: '3.8'

services:
  main:
    image: postgres
    labels:
      svc: "live.postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ITpg`01M[ls94l7xWD?n94hb0SL|r)
      POSTGRES_DB: guille_total_db
